{
 "title": "Basetime",
 "time": { "from": "2025-07-03T10:00:00.000Z", "to": "2026-03-30T09:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "GPS_Location",
    "label": "GPS_Location",
    "query": "noord_west_boog_01,noord_west_boog_02,noord_west_boog_03,noord_oost_boog_01,noord_oost_boog_02,noord_oost_boog_03,zuid_oost_boog_01,zuid_oost_boog_02,zuid_oost_boog_03,zuid_west_boog_01,zuid_west_boog_02,zuid_west_boog_03"
   },
   {
    "name": "Moving_Average",
    "label": "Moving Average",
    "query": "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,20,40,60,80,100"
   }
  ]
 },
 "panels": [
  {
   "title": "Basetime Monitoring",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "SELECT 'noord_west_boog_01' AS name, MAX(wgs84_latitude)  AS lat,\r\n       MAX(wgs84_longitude) AS lon\r\nFROM basetime_data.noord_west_boog_01\r\n\r\nUNION ALL\r\nSELECT 'noord_west_boog_02', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.noord_west_boog_02\r\n\r\nUNION ALL\r\nSELECT 'noord_west_boog_03', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.noord_west_boog_03\r\n\r\nUNION ALL\r\nSELECT 'noord_oost_boog_01', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.noord_oost_boog_01\r\n\r\nUNION ALL\r\nSELECT 'noord_oost_boog_02', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.noord_oost_boog_02\r\n\r\nUNION ALL\r\nSELECT 'noord_oost_boog_03', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.noord_oost_boog_03\r\n\r\nUNION ALL\r\nSELECT 'zuid_oost_boog_01', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_oost_boog_01\r\n\r\nUNION ALL\r\nSELECT 'zuid_oost_boog_02', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_oost_boog_02\r\n\r\nUNION ALL\r\nSELECT 'zuid_oost_boog_03', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_oost_boog_03\r\n\r\nUNION ALL\r\nSELECT 'zuid_west_boog_01', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_west_boog_01\r\n\r\nUNION ALL\r\nSELECT 'zuid_west_boog_02', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_west_boog_02\r\n\r\nUNION ALL\r\nSELECT 'zuid_west_boog_03', MAX(wgs84_latitude), MAX(wgs84_longitude)\r\nFROM basetime_data.zuid_west_boog_03;\r\n"
    }
   ]
  },
  {
   "title": "Displacement Relative To The First Measurement $GPS_Location",
   "type": "timeseries",
   "description": "Displacement relative to the first measurement: For each timestamp, the displacement in each coordinate (easting, northing, height) is calculated relative to the first GPS measurement.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "\r\nWITH Deltas AS (\r\n    SELECT\r\n        measurement_timestamp as time,\r\n        local_easting - AVG(local_easting) OVER (ORDER BY time ASC) AS delta_easting,\r\n        local_northing - FIRST_VALUE(local_northing) OVER (ORDER BY time ASC) AS delta_northing,\r\n        local_height - FIRST_VALUE(local_height) OVER (ORDER BY time ASC) AS delta_height\r\n    FROM\r\n        basetime_data.$GPS_Location\r\n    ORDER BY time ASC\r\n)\r\nSELECT\r\n    time,\r\n    delta_height * 1000 AS \"Vertical Displacement (mm)\",\r\n    (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2))) * 1000 AS \"Horizontal Displacement (mm)\",\r\n    (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2) + POW(delta_height, 2))) * 1000 AS \"Total 3D Displacment (mm)\"\r\n\r\nFROM\r\n    Deltas\r\nORDER BY\r\n    time ASC;"
    }
   ]
  },
  {
   "title": "Cumulative Displacement (Relative to Previous Measurement) $GPS_Location",
   "type": "timeseries",
   "description": "Displacement between consecutive measurements: The function compares each value (easting, northing, height) with the previous row, and calculates the change in position between consecutive timestamps.\n\nThis helps you track movement over time, and you can detect trends or shifts in the data.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "WITH Deltas AS (\r\n    SELECT\r\n        measurement_timestamp AS time,\r\n        local_easting - LAG(local_easting) OVER (ORDER BY measurement_timestamp ASC) AS delta_easting,\r\n        local_northing - LAG(local_northing) OVER (ORDER BY measurement_timestamp ASC) AS delta_northing,\r\n        local_height - LAG(local_height) OVER (ORDER BY measurement_timestamp ASC) AS delta_height\r\n    FROM\r\n        basetime_data.$GPS_Location\r\n    ORDER BY time ASC\r\n)\r\nSELECT\r\n    time,\r\n    delta_height * 1000 AS \"Vertical Displacement (mm)\",\r\n    (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2))) * 1000 AS \"Horizontal Displacement (mm)\",\r\n    (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2) + POW(delta_height, 2))) * 1000 AS \"Total 3D Displacement (mm)\"\r\nFROM\r\n    Deltas\r\nWHERE\r\n    delta_easting IS NOT NULL \r\nORDER BY\r\n    time ASC;\r\n"
    }
   ]
  },
  {
   "title": "Horizontal Vertical & 3D Moving Average: The average of the last $Moving_Average values for displacement. $GPS_Location",
   "type": "timeseries",
   "description": "Moving Average:\n\nVertical Moving Average: The average of the last $Moving_Average values for vertical displacement.\n\nHorizontal Moving Average: The average of the last $Moving_Average values for horizontal displacement.\n\nTotal 3D Moving Average: The average of the last $Moving_Average values for the total 3D displacement.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "WITH Deltas AS (\r\n    SELECT\r\n        measurement_timestamp AS time,\r\n        local_easting - LAG(local_easting) OVER (ORDER BY measurement_timestamp ASC) AS delta_easting,\r\n        local_northing - LAG(local_northing) OVER (ORDER BY measurement_timestamp ASC) AS delta_northing,\r\n        local_height - LAG(local_height) OVER (ORDER BY measurement_timestamp ASC) AS delta_height\r\n    FROM\r\n        basetime_data.$GPS_Location\r\n    ORDER BY time ASC\r\n)\r\nSELECT\r\n    time,\r\n    AVG(delta_height) OVER (ORDER BY time ASC ROWS BETWEEN $Moving_Average PRECEDING AND CURRENT ROW) * 1000 AS \"Vertical Moving Avg (mm)\",\r\n    AVG(SQRT(POW(delta_easting, 2) + POW(delta_northing, 2))) OVER (ORDER BY time ASC ROWS BETWEEN $Moving_Average PRECEDING AND CURRENT ROW) * 1000 AS \"Horizontal Moving Avg (mm)\",\r\n    AVG(SQRT(POW(delta_easting, 2) + POW(delta_northing, 2) + POW(delta_height, 2))) OVER (ORDER BY time ASC ROWS BETWEEN $Moving_Average PRECEDING AND CURRENT ROW) * 1000 AS \"Total 3D Moving Avg (mm)\"\r\n\r\nFROM\r\n    Deltas\r\nWHERE\r\n    delta_easting IS NOT NULL\r\nOrder by\r\n    time ASC\r\n"
    }
   ]
  },
  {
   "title": "$GPS_Location Easting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "SELECT measurement_timestamp as time, local_easting as Easting FROM basetime_data.$GPS_Location ORDER BY time ASC\r\n"
    }
   ]
  },
  {
   "title": "$GPS_Location Northing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "SELECT measurement_timestamp as time, local_northing as Northing FROM basetime_data.$GPS_Location ORDER BY time ASC\r\n-- WITH Deltas AS (\r\n--     SELECT\r\n--         measurement_timestamp as time,\r\n--         local_easting - FIRST_VALUE(local_easting) OVER (ORDER BY time ASC) AS delta_easting,\r\n--         local_northing - FIRST_VALUE(local_northing) OVER (ORDER BY time ASC) AS delta_northing,\r\n--         local_height - FIRST_VALUE(local_height) OVER (ORDER BY time ASC) AS delta_height\r\n--     FROM\r\n--         basetime_data.$GPS_Location\r\n-- )\r\n-- SELECT\r\n--     time,\r\n--     delta_height * 1000 AS \"Vertical Displacement\",\r\n--     (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2))) * 1000 AS \"Horizontal Displacement\",\r\n--     -- Add this line for total 3D displacement\r\n--     (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2) + POW(delta_height, 2))) * 1000 AS \"Total 3D Displacment\"\r\n-- FROM\r\n--     Deltas\r\n-- ORDER BY\r\n--     time ASC;"
    }
   ]
  },
  {
   "title": "$GPS_Location Hoogte",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "SELECT measurement_timestamp as time, local_height as Hoogte FROM basetime_data.$GPS_Location ORDER BY time ASC\r\n-- WITH Deltas AS (\r\n--     SELECT\r\n--         measurement_timestamp as time,\r\n--         local_easting - FIRST_VALUE(local_easting) OVER (ORDER BY time ASC) AS delta_easting,\r\n--         local_northing - FIRST_VALUE(local_northing) OVER (ORDER BY time ASC) AS delta_northing,\r\n--         local_height - FIRST_VALUE(local_height) OVER (ORDER BY time ASC) AS delta_height\r\n--     FROM\r\n--         basetime_data.$GPS_Location\r\n-- )\r\n-- SELECT\r\n--     time,\r\n--     delta_height * 1000 AS \"Vertical Displacement\",\r\n--     (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2))) * 1000 AS \"Horizontal Displacement\",\r\n--     -- Add this line for total 3D displacement\r\n--     (SQRT(POW(delta_easting, 2) + POW(delta_northing, 2) + POW(delta_height, 2))) * 1000 AS \"Total 3D Displacment\"\r\n-- FROM\r\n--     Deltas\r\n-- ORDER BY\r\n--     time ASC;"
    }
   ]
  },
  {
   "title": "GPS Temperature  $GPS_Location",
   "type": "timeseries",
   "description": "Displacement relative to the first measurement: For each timestamp, the displacement in each coordinate (easting, northing, height) is calculated relative to the first GPS measurement.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "basetime_data",
     "rawSql": "\r\n    SELECT\r\n        measurement_timestamp as time,\r\n\r\n        temperature_celsius\r\n    FROM\r\n        basetime_data.$GPS_Location\r\n    ORDER BY time ASC\r\n"
    }
   ]
  }
 ]
}